# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Орищин Юрій Михайлович
subtitle: (1942-2021)
email: yurioryshchyn@mail.ua
description: > # this means to ignore newlines until "baseurl:"
  Сайт пам'яті Ю. М. Орищина, професора кафедри фізики НЛТУ України
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://oryshchyn.github.io" # the base hostname & protocol for your site
github_username:  oryshchyn

# Build settings
markdown: kramdown
